VITE_BASE_URL2=https://payina-be-6f08cdfb4414.herokuapp.com/api
// VITE_BASE_URL2=https://payina-be-6f08cdfb4414.herokuapp.com/api
VITE_FETCH_NETWORKS=https://payina-wallet-service-api.onrender.com/api/v1/vas/biller-enquiry-slug/AIRTIME_AND_DATA
VITE_FETCH_DATA_PLANS=https://payina-wallet-service-api.onrender.com/api/v1/vas/package-enquiry-slug
VITE_INITIALIZE_PAYMENT=https://payina-wallet-service-api.onrender.com/api/v1/bill/initialize
VITE_VEND_VALUE=https://payina-wallet-service-api.onrender.com/api/v1/vas/vend-value-non-payina-customer
VITE_FETCH_SERVICES=https://payina-wallet-service-api.onrender.com/api/v1/vas/biller-groups
VITE_FETCH_BILLER_PLANS=https://payina-wallet-service-api.onrender.com/api/v1/vas/package-enquiry-slug
VITE_FETCH_BILLER_DETAILS=https://payina-wallet-service-api.onrender.com/api/v1/vas/biller-enquiry-id
VITE_FETCH_BILLER_GROUPS=https://payina-wallet-service-api.onrender.com/api/v1/vas/biller-groups